### PR TITLE
Externalize/metadata grapher

### PR DESCRIPTION
**Pull request by Nono1971**
Following #476 I made my changes from an up to date version...

This is about externalizing the MetadataGrapher, so could be used as well by My symfony's onurb/doctrine-yuml-bundle and DoctrineOrmModule :)

@Ocramius suggested that here #430 I finaly did it, after refactoring the class... so, if you always agree with that, let's go ! :)
You can go check the code here : https://github.com/Nono1971/Doctrine-MetadataGrapher.
I implemented the same tests that where used here (modified after the new bug I found next week and the patch used here : #482) .

### CODE REVIEW

**Comment by Nono1971** [comment]
arf... hope I didn't rebased too much :s ??

**Comment by Ocramius** [comment]
@Nono1971 let's simplify things a bit:

 1. make a fresh clone of the repository
 2. `git checkout -b my-branch`
 3. apply https://github.com/doctrine/DoctrineORMModule/pull/483/commits/7b6d230da4ef5acd2da57ad5938716ea177ee34b and https://github.com/doctrine/DoctrineORMModule/pull/483/commits/d8a32bbff6746d00c087e26390b5d92c395dff27 manually
 4. commit
 5. push

**Comment by Ocramius** [comment]
Closing here

**Comment by Nono1971** [comment]
thanks for you patience with the noob I still am with github :D

Yes, a new fresh clone will be better... for the four little changes I only have to do :D 

Do it quick !

**Comment by Ocramius** [comment]
Moved to #485

**Pull request closed without merging**
