### PR TITLE
Fix PHPStan failures.

### PR DESCRIPTION
**Pull request by demiankatz**

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Does this impact 5.4.x only? Or is 5.3.x impacted as well?

**Comment by demiankatz** [comment]
@greg0ire, I haven't tested earlier branches and am not currently in a position to do it (upgrading my VM, which will be tied up for the rest of the day)... but it would be easy enough to find out by checking out the branch and running `composer run phpstan` if you don't mind. :-)

**Comment by greg0ire** [comment]
The answer is a clear yes. Let me rebase and retarget your branch.

**Comment by demiankatz** [comment]
Thanks, @greg0ire!

**Comment by greg0ire** [comment]
Thanks @demiankatz !

**Pull request merged**
