### PR TITLE
Move supports to doctrine\migrations in another module

### PR DESCRIPTION
**Pull request by gianarb**
Move doctrine\migrations supports in another module

I spoke with @Ocramius and I'm here to propose this solution.
First because `doctrine2` and `doctrine\migrations` are two different projects and in my opinion is a bad idea merge them in one project.

In my opinion splitting this could increase mantainability costs but will give us a better way to manage such modules.

I submit now this proposal because this increases module's stability.. WIP for 1.0.0 :)

Here new [DoctrineMigrationsModule](https://github.com/gianarb/DoctrineMigrationsModule) proposal

### CODE REVIEW

**Comment by samsonasik** [comment]
docs/migrations.md need to be moved too?

**Comment by samsonasik** [comment]
composer.json need to be updated to require doctrinemigrationmodule imo

**Comment by gianarb** [comment]
oh yes this PR has a lot of problem.. :D it's here for feedback about the idea :)..

But thanks for this check!! :) I update my PR!
@samsonasik if you use migrations can you try doctrine-module-migrations?
Thanks

**Comment by codeliner** [comment]
:+1: I often use doctrine/dbal + migrations, but find myself in the situation to install and configure the complete ORM to only get doctrine/migrations support in ZF2. Splitting it into a separate repo would be great.

**Comment by gianarb** [comment]
@codeliner would you help us? :) Try [gianarb/DoctrineMigrationsModule](https://github.com/gianarb/DoctrineMigrationsModule) please! :) 
Thanks!

**Comment by codeliner** [comment]
@gianarb ah great. I will try it. When it is working I will add it to my new cqrs sample app: https://github.com/prooph/proophessor-do :-)

**Comment by gianarb** [comment]
Thanks I expect your feedback! :) :+1:

**Comment by netiul** [comment]
:+1:

**Comment by samsonasik** [comment]
@gianarb I have tried https://github.com/gianarb/DoctrineMigrationsModule by requiring that : 
```
     "doctrine/doctrine-orm-module": "0.9.*",
        "doctrine/doctrine-migrations-module": "dev-master"
```
and got error : 
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package doctrine/doctrine-migrations-module could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Installation request for sitrunlab/learnzf2 0.2.x-dev -> satisfiable by sitrunlab/learnzf2[0.2.x-dev].
    - sitrunlab/learnzf2 0.2.x-dev requires doctrine/doctrine-migrations-module dev-master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

**Comment by samsonasik** [comment]
oh, seems i need minimum-stability...

**Comment by samsonasik** [comment]
@gianarb it seems https://github.com/gianarb/DoctrineMigrationsModule is not composer-able to install yet...

**Comment by gianarb** [comment]
In this moment doctrineMigrations has not tag.. In this moment this feature is freezed because I wait feedback about this issue :) https://github.com/gianarb/DoctrineMigrationsModule/issues/2

**Comment by samsonasik** [comment]
I will try git clone, wait a minute

**Comment by samsonasik** [comment]
@gianarb  i re-tried and got error : 
```
PHP Fatal error:  Class 'DoctrineMigrationsModule\Service\MigrationsCommandFactory' not found in /Users/samsonasik/www/LearnZF2/vendor/doctrine/doctrine-module/src/DoctrineModule/ServiceFactory/AbstractDoctrineServiceFactory.php on line 57
```
it seems my dependency just not uptodate. I'm basically +1 for it.

**Comment by codeliner** [comment]
@samsonasik What do you think about the issues mentioned in gianarb/DoctrineMigrationsModule#2?

**Comment by gianarb** [comment]
DoctrineORMModule will maintain doctrine\migrations..
https://twitter.com/GianArb/status/601072388982362112

:) Thanks

**Pull request closed without merging**
