### PR TITLE
Fixed missing version

### PR DESCRIPTION
**Pull request by gianarb**
I have forgotten to change version of this lib

:sos: 

ping @Ocramius

### CODE REVIEW

**Comment by mpalourdio** [comment]
Will you re-tag 0.9.0 ? It may break those that are bases on composer.lock no ? You'd better tag 0.9.1 IMO.

**Comment by Ocramius** [comment]
Re-tagging is no-go

**Comment by gianarb** [comment]
I have submitted this PR because I don't know what is a good flow to resolve this problem.. :)

can I update this PR with 0.9.1 and tag release?
is it good about you? :)
Thanks

**Comment by gianarb** [comment]
I don't know why but the tests are broken.. :) I can try to find the problem

**Pull request merged**
