### PR TITLE
Re-enable scrutinizer code coverage

### PR DESCRIPTION
**Pull request by mpalourdio**
Attempt in order to re-enable scrutinizer-ci code coverage

### CODE REVIEW

**Comment by mpalourdio** [comment]
Seems ok now https://scrutinizer-ci.com/g/doctrine/DoctrineORMModule/inspections/641fe8d7-d877-4da6-a2cc-e698547f2000

I think the badge will be ok if a travis build is fired from master now.

**Comment by Ocramius** [comment]
@mpalourdio thanks, merged :-) Let's hope for green!

**Comment by mpalourdio** [comment]
such badge, much coverage

**Comment by Ocramius** [comment]
So amaze!

**Pull request merged**
