### PR TITLE
externalize MetadataGrapher to a library

### PR DESCRIPTION
**Pull request by Nono1971**
Hi, as suggested By Ocramius few month ago... I propose to externalize the Yuml MetadataGrapher into an external library.

I left it behind (and almost forgot it)... but I have decided refactoring my class again... that instead of modifiing both sides again... It's infact really better to finaly do it :)
 You can go there to check if the library pleases to you : https://github.com/Nono1971/Doctrine-MetadataGrapher

### CODE REVIEW

**Comment by gianarb** [comment]
@Ocramius pleae give some feedback about this idea.. It's a next external dependencies.. I don't really like that but if you like the idea we can merge :)

Thanks @Nono1971 for your effort!

**Comment by Nono1971** [comment]
for your help, it was suggested here : #430

**Comment by Nono1971** [comment]
Well... I just found a bug not covered by tests into the library... wich is not present without my refactoring... 

 I'll work on it after my job... don't merge now ;)

**Comment by Nono1971** [comment]
Hello,

I worked on it... and found a solution... but I have a problem testing it... You might help maybe ^^ 

let's describe the problem.

The bug came from the Metadata::getClassReverseAssociationName() method... Wich was the same used here before my fix : 

    private function getClassReverseAssociationName(ClassMetadata $class1, ClassMetadata $class2)
    {
        foreach ($class2->getAssociationNames() as $class2Side) {
            $targetClass = $this->getClassByName($class2->getAssociationTargetClass($class2Side));
            if ($class1->getName() === $targetClass->getName()) {
                return $class2Side;
            }
        }

        return null;
    }

I replaced the failing method by this : 

    /**
     * @param \Doctrine\Common\Persistence\Mapping\ClassMetadata $class1
     * @param string $association
     * @return string|null
     */
    private function getClassReverseAssociationName(ClassMetadata $class1, $association)
    {
        if ($class1->getAssociationMapping($association)['isOwningSide']) {
            return $class1->getAssociationMapping($association)['inversedBy'];
        } else {
            return $class1->getAssociationMapping($association)['mappedBy'];
        }
        return null;
    }

Of course I changed also the call of the method to replace the class by the association name into getAssociationString() method : 

    $class2SideName = $this->getClassReverseAssociationName($class1, $association);


It works perfectly ! :)

Now are the troubles comming... Tests !!

I use the ClassMetadataInfo::getAssociationMapping() method, wich was not used before... and I'd like to test it correctly... but this method is not in the interface Doctrine\Common\Persistence\Mapping\ClassMetadata so I can't mock the method without changing the interface... wich is in doctrine/common... (and also implemented into doctrine/odm wich should be fixed if the interface would change : the doctrine/odm ClassMetadataInfo doesn't implements this method yet of course ^^).

I pass all tests changing manually the interface doctrine/common... only adding the getClassReverseAssociationName() method.

Do you think the interface could be changed on doctrine/common ? 
should I make a pull request there or would you as it fixes the bug here to ? 
=> I make a push with the failing testcase here... (I'll edit to link the pull request))

If the interface could be changed, I could version my package as it would fix bug here too :)

**Comment by Nono1971** [comment]
I pushed the bug testCase (and partial fix) here #482

**Comment by Nono1971** [comment]
I applied my travis ugly fix in my repo, so all tests are good... I version it and you can merge :)

**Comment by Nono1971** [comment]
Damn, After ocramius remark here #482 , I look for the tree... and I realise that I really started from too far, forgotting to pull changes on master before creating the branch... I close this pull request and create a clean new one, with a package up to date

**Comment by Ocramius** [comment]
Moved to #485

**Pull request closed without merging**
