### PR TITLE
Change build paremeters to prevent errors with hhvm and php7

### PR DESCRIPTION
**Pull request by mpalourdio**
See https://github.com/doctrine/DoctrineModule/pull/512 for reference.

### CODE REVIEW

**Comment by mpalourdio** [comment]
This PR could be useless if a workaround is found for ZF2. I've opened an issue here

**Comment by mpalourdio** [comment]
Fixed in https://github.com/zendframework/zf2/pull/7571

**Comment by mpalourdio** [comment]
I ended up with just leaving the commit that fixes the builds. It is stille relevant as with phpunit 4.*, hhvm reports a wrong convering percentage, and with php7, xdebug is not loaded, so no coverage at all.

**Comment by gianarb** [comment]
Thanks

**Pull request merged**
