### PR TITLE
Drop PHP 7.4

### PR DESCRIPTION
**Pull request by demiankatz**
As proposed on #734, this PR drops support for PHP 7.4, since it has passed end of life. This may simplify some of our continuous integration issues.

TODO
- [x] Make style check pass

### CODE REVIEW

**Comment by demiankatz** [comment]
I based this on https://github.com/doctrine/DoctrineModule/commit/5d6f2aa03b1f0912d092bfa30be5562ccf0b700e -- pretty sure I didn't miss anything. We'll see if CI passes. :-)

**Comment by demiankatz** [comment]
Looks like everything is passing except style checks -- raising the PHP version has allowed the style checker to make some new suggestions. @greg0ire / @TomHAnderson, would you like me to implement these changes? I'm willing to, but won't invest time in it until I'm sure somebody wants me to. :-)

**Comment by TomHAnderson** [comment]
Laminas has moved past 7.4 so I'm comfortable with this PR.  Please keep up your excellent work.

**Comment by demiankatz** [comment]
Thanks, @TomHAnderson -- since I had some momentum, I figured I might as well use it to clean up the styles here, so I believe this is ready to merge now if you're willing. I guess the only question is whether this requires a 6.0.x branch or not -- I'm unsure of the release practices here.

**Review by TomHAnderson — APPROVED** [review]

**Pull request merged**
