### PR TITLE
support psr/container 2

### LINKED ISSUE #752: orm3 compatibility
[Doctrine ORM 3](https://github.com/doctrine/orm/releases/tag/3.0.0) has been released. The module requires the corresponding compatibility.

### PR DESCRIPTION
**Pull request by pascalheidmann**
`psr/container` 1 and 2 are basically the same but with type hints/return types

### CODE REVIEW

**Comment by driehle** [comment]
LGTM, but we'll first need to the same for [DoctrineModule](https://github.com/doctrine/DoctrineModule/), otherwise this won't help. Would you mind providing a PR there as well?

**Review by TomHAnderson — APPROVED** [review]

**Comment by snapshotpl** [comment]
Every run in actions install v1 because doesn't meet dependecy requirements (e.g. laminas-servicemanager)

**Comment by TomHAnderson** [comment]
DoctrineModule PR https://github.com/doctrine/DoctrineModule/pull/829

**Comment by SenseException** [comment]
I haven't checked every Continuous Integration build, just one lowest and one highest, but psr/container 1 is currently the only used version.

**Review by driehle — CHANGES_REQUESTED** [review]
It doesn't make any sense to support psr/container 2 unless we upgrade laminas-servicemanager to 4.0, as 3.x supports psr/container 1 only. For that, however, we will need to go into a new major release. I have changed the milestone accordingly.

Let's wait for laminas-servicemanager 4.0 to be published. An RC is available already.

**Pull request closed without merging**
