### PR TITLE
Drop `container-interop/container-interop`

### PR DESCRIPTION
**Pull request by tomudding**
As suggested in #728 this drops the abandoned `container-interop/container-interop` in favour of `psr/container`. This means that the `Interop\Container\ContainerInterface` interface is replaced with `Psr\Container\ContainerInterface`.

Unlike doctrine/DoctrineModule#792 not all changed signatures are in `final` classes, specifically the `CliConfigurator`. This may require bumping `laminas/laminas-servicemanager` to at least `v3.11.0`, @driehle please advise.

### CODE REVIEW

**Comment by tomudding** [comment]
I am aware of the failing tests, I will address these in a bit.

**Comment by fezfez** [comment]
seem good to me :1st_place_medal:

**Comment by driehle** [comment]
> This may require bumping `laminas/laminas-servicemanager` to at least `v3.11.0`, @driehle please advise.

Indeed, we need to bump laminas-servicemanager to the version introducing class aliases for the interop and the Psr containers. For the records, boesing has explained this here: https://github.com/php-fig/container/issues/37

Please bump to ^3.17.0. Otherwise this PR looks fine.

**Comment by tomudding** [comment]
> Please bump to ^3.17.0. Otherwise this PR looks fine.

I have amended my first commit to bump the version to ensure correct history. Thank you for your time taking a look at this :)

**Review by driehle — APPROVED** [review]

**Pull request merged**
