### PR TITLE
Add support for DBAL Middlewares

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by snapshotpl** [comment]
Looks like not related errors now.

**Comment by driehle** [comment]
Could it be an issue with dbal 3.2.0? I saw tests passing for dbal ^3.1.0 with lowest and failing for ^3.1.0 with highest (which installes 3.2.1).

**Comment by driehle** [comment]
@snapshotpl Could you please squash [12684f7](https://github.com/doctrine/DoctrineORMModule/pull/708/commits/12684f7b9f0636bd1931e109a2a2096d015b24b7) into [e2f5bd6](https://github.com/doctrine/DoctrineORMModule/pull/708/commits/e2f5bd6d51bb976b1e3f58fdd53a33a2f52da0a5) and then rebase your changes on the latest `5.1.x` branch? This should solve the issues with the broken pipelines.

**Comment by snapshotpl** [comment]
@driehle ready to go

**Review by driehle — APPROVED** [review]
LGTM 🚢

**Pull request merged**
