### PR TITLE
::class update and test update 

### PR DESCRIPTION
**Pull request by kokspflanze**
changed to `::class` in tests and readme
update to `createMock`, if we call only `getMockBuilder` + `getMock`

like in https://github.com/doctrine/DoctrineORMModule/pull/497 written

### CODE REVIEW

**Comment by webimpress** [comment]
@kokspflanze I like it, but it will be conflicted with my PR #507 and duplicate some my work provided in this PR. I thought about it as next step after merging #507...

**Comment by kokspflanze** [comment]
@webimpress yeah i already saw it, i hope it works without a merge conflict, but we will see=)

**Comment by kokspflanze** [comment]
ping @gianarb

**Comment by TomHAnderson** [comment]
Please rebase this PR

**Comment by kokspflanze** [comment]
@TomHAnderson already merged master into my branch

**Comment by TomHAnderson** [comment]
I'm fine with merging this to master but I'd like to get your phpuinit 6 changes in for the next release.  Are you ok with this, @kokspflanze ?

**Pull request merged**
