### PR TITLE
Fix version test to new Doctrine version

### PR DESCRIPTION
**Pull request by eminetto**

### CODE REVIEW

**Comment by Ocramius** [comment]
@eminetto what was the error you were getting prior to this change?

**Comment by eminetto** [comment]
I receive an error regarding to Second Level Cache, because it is not enabled.

**Comment by eminetto** [comment]
To be more specific, 
```
$entityManager->getCache()
```
returns null

**Comment by Ocramius** [comment]
@gianarb poke

**Comment by gianarb** [comment]
Version::compare description is 
> Returns -1 if older, 0 if it is the same, 1 if version passed as argument is newer.

`Version::compare('2.5.0') <= 0` the correct check shoud be it..
What do you think @Ocramius @eminetto?

I'm working to enable this matrix #432  to test this PR

**Comment by Ocramius** [comment]
#432 seems to be a better fix (with tests).

See comments there, closing here.

**Pull request closed without merging**
