### PR TITLE
default query hints

### PR DESCRIPTION
**Pull request by Perfect-Web**

### CODE REVIEW

**Comment by gianarb** [comment]
Can you describe a use case? We can use it to improve the docs for example :)
And can you add a little test to mock this feature? Thanks

**Comment by Perfect-Web** [comment]
this is for default hints introduces to doctrine 2.5 when you wanna use custom walkers

**Comment by gianarb** [comment]
Hi! Can you add a reference about this feature into the docs?

Example of use, configuration.. No tests? mock config and test if `setDefaultQueryHints`will be call for example..

This is a new feature and I have no hurry to merge it.. I prefer that is complete of this stuff..

What do you think?

**Comment by Perfect-Web** [comment]
i agree with you but i really dont have time for the tests, even tho is such a small test, maybe when o do get some spare time ...

**Comment by Perfect-Web** [comment]
@gianarb can we merge this ?

**Comment by Perfect-Web** [comment]
@Ocramius can we merge this now that it passes ?

**Comment by Perfect-Web** [comment]
@gianarb added

**Comment by gianarb** [comment]
Thanks @Perfect-Web

**Comment by Perfect-Web** [comment]
@gianarb something is wrong ... i dont see this changes anywhere on master ...

**Comment by Perfect-Web** [comment]
@gianarb can you check this ? the code is not merged ...

**Pull request merged**
