### PR TITLE
update comment block in Module.php as no Module::getAutoloaderConfig() 

### PR DESCRIPTION
**Pull request by samsonasik**
means it must be using composer

### CODE REVIEW

**Comment by Ocramius** [comment]
@samsonasik thanks!

**Comment by samsonasik** [comment]
Actually, after I re-think about it, the comment block itself need to be updated to make it work without composer with Zend\Loader ?

Warm regards,

Abdul Malik Ikhsan

Pada 27 Feb 2015, pukul 05.23, Marco Pivetta <notifications@github.com> menulis:

**Comment by samsonasik** [comment]
or another option. revert this change and add Module::getAutoloaderConfig() ?

Warm regards,

Abdul Malik Ikhsan

Pada 27 Feb 2015, pukul 05.23, Marco Pivetta <notifications@github.com> menulis:

**Comment by Ocramius** [comment]
@samsonasik the module does not need to work without composer

**Comment by samsonasik** [comment]
@Ocramius so this file can be deleted, then ?

**Comment by mpalourdio** [comment]
If you delete it, you need to add a 'classmap' entry in composer.json, that reference the Module class as the ModuleManager expects to find Module.php under /src

**Comment by Ocramius** [comment]
@mpalourdio no need: the ModuleManager only autoloads what isn't autoloadable.

**Pull request merged**
