### PR TITLE
ZF3 compatibility

### PR DESCRIPTION
**Pull request by webimpress**
In difference to #479 this PR add ZF3 compatibility but also __keep ZF2 compatibility__.

__There is no any BC breaks ! ! !__ 😄

Other changes introduced in #479 could be done later.

It depends on https://github.com/doctrine/DoctrineModule/pull/567

The only problem was with `zend-mvc-console` (over ZF3) so please see `suggest` section in `composer.json` and travis configuration.

Thoughts?

### CODE REVIEW

**Comment by thomasvargiu** [comment]
@webimpress You need to change this to be compatible with zend-router:
https://github.com/doctrine/DoctrineORMModule/blob/2e0660bc6a7d2f28df6bc1a96711d0c981ff0afa/config/module.config.php#L260

**Comment by MatthiasKuehneEllerhold** [comment]
I can confirm that the current master is broken, because 
* Zend\Mvc\Router\Http\Literal got renamed to Zend\Router\Http\Literal (as reported by @thomasvargiu)
* it uses the (not-registered) "zendDeveloperToolsTime" view helper (this got fixed in @webimpress other PR)
* the ORM Modules requires "doctrine/doctrine-module": "dev-feature/zf3compat" (@webimpress branch) which should be renamed to "dev-master"

**Comment by webimpress** [comment]
@MatthiasKuehneEllerhold please have a look on changes provided by @thomasvargiu in #494

**Comment by MatthiasKuehneEllerhold** [comment]
Yep all 3 problems are fixed and my app is working again. Thanks everybody!

**Comment by devtosystems** [comment]
[InvalidArgumentException]
  Could not find package doctrine/doctrine-orm at any version for your minimum-stability (dev). C
  heck the package spelling or your minimum-stability

**Comment by MatthiasKuehneEllerhold** [comment]
Sorry, the missing view-helper "zendDeveloperToolsTime" wasnt fixed. Ive created #496 to fix it.

**Comment by Slamdunk** [comment]
@gianarb may you tag the current master, perhaps with a non-stable one ([alpha, beta or RC](https://getcomposer.org/doc/04-schema.md#minimum-stability))?

**Pull request merged**
