### PR TITLE
add connection and schema zend diagnostics

### PR DESCRIPTION
**Pull request by abacaphiliac**
* add zendframework/zenddiagnostics
* add connection diagnostic, with factory
* add symfony-command diagnostic, with schema validator diagnostic factory
* add example diagnostic config (dist), since we cannot be sure that consumers are using the default connection (orm_default).

sample output:
```
[vagrant@vagrant]$ php public/index.php diag -v --debug
  OK   ZF: PHP Version: Current PHP version is 5.6.5
       ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
       '5.6.5'
       ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  OK   DoctrineORMModule: Database Connection: Doctrine\DBAL\Connections\MasterSlaveConnection
       ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
       array (
         'slave' => 'connected',
         'master' => 'connected',
       )
       ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 FAIL  DoctrineORMModule: ORM Validate Schema: Doctrine\ORM\Tools\Console\Command\ValidateSchemaCommand
       ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
       array (
         0 => '[Mapping]  OK - The mapping files are correct.',
         1 => '[Database] FAIL - The database schema is not in sync with the current mapping file.',
       )
       ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  OK   ZF\Apigility\Admin: Config File Writable

1 failures, 0 warnings, 3 successful checks.                                                                                                                                         
```

### CODE REVIEW

**Comment by gianarb** [comment]
Personally I prefer add a suggestion package on composer.json and suggest a new module that manage this integration.. @Ocramius what do you think about this point?

@abacaphiliac could be good for you create a new bridge?

**Comment by Ocramius** [comment]
Pretty much agree, @gianarb.

The `zendframework/zenddiagnostics` is opt-in, so should it be when using this module...

**Comment by abacaphiliac** [comment]
thanks for the suggestion guys. i'll create a module for the integration.

**Comment by abacaphiliac** [comment]
@gianarb if you have some time, please tell me what you think. i'm open to suggestions. it would be awesome if i could make something worthy of a mention in doctrine/doctrine-orm-module!

https://packagist.org/packages/abacaphiliac/doctrine-orm-diagnostics-module

**Pull request closed without merging**
