### PR TITLE
PHPUnit update

### PR DESCRIPTION
**Pull request by kokspflanze**
changed `getMock` to `getMockBuilder` for PHPUnit 5.4+
changed `setExpectedException` to `expectException` it is already deprecated

changed arraysyntax in unittests
updated composer.json to min PHPUnit 5.5.0

### CODE REVIEW

**Comment by webimpress** [comment]
@kokspflanze `getMock` is deprecated but you can use `createMock` instead in PHPUnit 5. It is shorter than `...->getMockBuilder(...)->getMock()`.

**Comment by gianarb** [comment]
Thanks @kokspflanze 

@Ocramius do we have a sort of standard? will we use createMock or getMockBuilder? 

👍 getMockBuilder
💯 createMock

Reaction please! @webimpress :)

**Comment by webimpress** [comment]
For me both are fine. Personally I'd prefer shorter version when possible. I would also go with `::class` notation, but it could be done later on in separate PR. It will be much nicer!

**Comment by kokspflanze** [comment]
about the `::class` i will create a new PR after my vacation

**Comment by gianarb** [comment]
Thanks a lot @kokspflanze

**Pull request merged**
