### PR TITLE
Remove zend-hydrator dependency

### PR DESCRIPTION
**Pull request by boesing**
Hey guys,

I am actually trying to migrate to `zendframework/zend-hydrator` v3.
This library is depending on v2 but dont even uses something of that library.

I've dropped the dependency and going to apply a PR to `doctrine/doctrine-module` after this.

### CODE REVIEW

**Comment by webimpress** [comment]
@boesing this is BC Break, please see: https://github.com/doctrine/DoctrineModule/pull/644 and also new repository we've created recently: https://github.com/doctrine/doctrine-zend-hydrator

**Comment by boesing** [comment]
@webimpress so its a BC break because we are removing a dependency which is not used by this library? 🤔

**Comment by webimpress** [comment]
@boesing yes, sorry, you are right, it will be BC Break only in DoctrineModule, not here, you are right !

**Comment by snapshotpl** [comment]
Hey folks, what about this?

**Comment by fezfez** [comment]
Any news ?

**Comment by shandyDev** [comment]
Maybe somebody just merge it? )

**Comment by snapshotpl** [comment]
@Ocramius @michalbundyra Can you merge and release this?

**Comment by TomHAnderson** [comment]
@michalbundyra I guess this comes back to your work on the hydrator.  Are you ready to move that forward?

**Comment by TomHAnderson** [comment]
This is the PR I think is holding this up:
https://github.com/doctrine/doctrine-zend-hydrator/pulls

I'd really like to see doctrine-zend-hydrator complete and used in
doctrine-orm-module
@michaelbundyra and I have had several back-and-forths about this.  Perhaps
it's time to regroup and focus on our next hydrator step.

**Comment by michalbundyra** [comment]
@TomHAnderson Please hold on couple more days - we are just about to launch Laminas, and then we can move on on these doctrine modules/hydrators.

**Comment by boesing** [comment]
I still think that this PR does not cause any issues.
This package itself has absolutely no relation to zendframework/zend-hydrator at all.
Thats why I initially created this.

Why would we keep an requirement, which is not used by this library?

**Comment by michalbundyra** [comment]
@boesing yeah, I forgot again and haven't checked.
@TomHAnderson This can be merged then.

**Comment by TomHAnderson** [comment]
Hydrator has been extracted to doctrine/doctrine-laminas-hydrator

**Comment by boesing** [comment]
@TomHAnderson no, it is still required in this package for *NO REASON*. Thats what this PR is all about.

I highly appreciate the new dependency of the doctrine-laminas-hydrator package in doctrine/doctrine-module but this package (orm-module) still depends on zend-hydrator without having any usage of any contents of that package.
Its just an empty dependency for nothing which blocks any user of this orm-module from upgrading to zend-hydrator v3 for example.

**Pull request closed without merging**
