### PR TITLE
Allow symfony/console ^6.0.0

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

**Review by greg0ire — CHANGES_REQUESTED** [review]
This does not result in the CI running the tests with Symfony 6: https://github.com/doctrine/DoctrineORMModule/runs/4377843680?check_suite_focus=true#step:7:115

**Comment by fezfez** [comment]
@greg0ire : i think it's because it depend on https://github.com/doctrine/DoctrineModule/pull/756

**Comment by greg0ire** [comment]
Let's put this PR on hold until that other one is merged and released then.

**Comment by fezfez** [comment]
@greg0ire : no problem ;)

**Comment by driehle** [comment]
DoctrineModule 4.4.0 with support for symfony/console ^6.0 is released. Please check again if it now works with DoctrineORMModule as well.

**Comment by fezfez** [comment]
@driehle  : seem to work : https://github.com/doctrine/DoctrineORMModule/runs/4383192912?check_suite_focus=true

**Comment by driehle** [comment]
Looks good 👍 

```
 - Locking symfony/console (v6.0.0)
```

Could you please squash your commits?

**Comment by fezfez** [comment]
@driehle : done

**Review by driehle — APPROVED** [review]

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
`Locking symfony/var-dumper (v5.4.0)` what's blocking the upgrade to `6.0.0`?

**Comment by driehle** [comment]
Not our fault 😇 

```
driehle:~/DoctrineORMModule$ composer why symfony/var-dumper
laminas/laminas-developer-tools  2.2.0  requires  symfony/var-dumper (^5.0.1)
```

Oh, and snapshotpl was faster than me opening a PR a laminas-developer-tools 😄 

- https://github.com/laminas/laminas-developer-tools/pull/42

**Comment by snapshotpl** [comment]
@driehle not related, but lucky!

**Pull request merged**
