### PR TITLE
PHP 8.3 support

### PR DESCRIPTION
**Pull request by TomHAnderson**
This PR will require at least the following:

* 8.3 support for [doctrine/DoctrineModule](https://github.com/doctrine/DoctrineModule)
  * 8.3 support for [laminas/laminas-cache-storage-adapter-filesystem](https://github.com/laminas/laminas-cache-storage-adapter-filesystem/pull/76)

Laminas must update their libraries first to support DoctrineModule

### CODE REVIEW

**Comment by FabianKoestring** [comment]
@TomHAnderson https://github.com/laminas/laminas-cache-storage-adapter-filesystem/releases/tag/2.4.0 has been released with 8.3 support. ✌️

**Comment by FabianKoestring** [comment]
@TomHAnderson JFYI https://github.com/doctrine/DoctrineModule/releases/tag/6.1.0 has been released. ✌️

**Comment by TomHAnderson** [comment]
```
 - laminas/laminas-developer-tools 2.3.0 requires php ^7.3 || ~8.0.0 || ~8.1.0 -> your php version (8.3.0) does not satisfy that requirement.
 ```
 
 I'm worried about this dependency.  The tools hasn't been touched since 2022.

**Comment by TomHAnderson** [comment]
```
 - laminas/laminas-developer-tools 2.3.0 requires php ^7.3 || ~8.0.0 || ~8.1.0 -> your php version (8.3.0) does not satisfy that requirement.
 ```

The last release of that library doesn't support 8.3:  https://github.com/laminas/laminas-developer-tools/blob/2.8.x/composer.json

Unreleased code is moving forward with 8.3 support.

**Comment by FabianKoestring** [comment]
@TomHAnderson https://github.com/laminas/laminas-developer-tools/releases/tag/2.9.0

**Comment by TomHAnderson** [comment]
I've reran the checks.  There's one problem with MigrationsCommandFactoryTest.  The `testDefineDependencyFactoryServicesFromConfig` test can no longer pass a string as a dependency factory service due to a change in migrations:  https://github.com/doctrine/migrations/pull/1363/files#diff-7b97541a9d8f1fd4102229408221c25b9785ad7d9b47cdfcba644ee93a00a0ffR308

The value of the dependency factory service is an id from the service manager.

**Comment by TomHAnderson** [comment]
See commit https://github.com/doctrine/DoctrineORMModule/pull/749/commits/2f117719b2adeffb3adb1bd6dddabc56f17b1a02 for the fix of my last note.

**Review by driehle — CHANGES_REQUESTED** [review]
Same as in doctrine/DoctrineModule#828: Please update PHP version of the other workflows to 8.3, i.e. coding standards, static analysis and composer lint. They need to run with the latest version, as the minimal version is automatically inflected.

**Comment by TomHAnderson** [comment]
@driehle in https://github.com/doctrine/DoctrineModule/pull/828#pullrequestreview-1816640056 you asked the workflows be set to 8.2 though the max version is 8.3.  Here you're asking for the same thing but I think you're asking fo 8.3.  If the correct version is 8.3 then we'll need to update DoctrineModule too.

**Comment by driehle** [comment]
@TomHAnderson Yes, my fault. Should be 8.3 (i.e. the latest).

**Review by driehle — APPROVED** [review]

**Pull request merged**
